name: Keep Render Awake

on:
  schedule:
    - cron: "*/12 0-16 * * *
"
  workflow_dispatch:

jobs:
  keep_awake:
    runs-on: ubuntu-latest
    steps:
      - name: Send login request to backend
        run: |
          RESPONSE=$(curl -s -L -X POST "http://holdsmart-be.onrender.com/auth/login" \
          -H "Content-Type: application/json" \
          -d '{"email": "${{ secrets.HOLDSMART_EMAIL }}", "password": "${{ secrets.HOLDSMART_PASSWORD }}"}' \
          -w "\n%{http_code}")

          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | head -n -1)

          echo "HTTP Status Code: $HTTP_STATUS"
          echo "API Response: $BODY"
